name: CI-CD-Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  # 1. BUILD
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install
    - run: echo "Build step done"

    - uses: actions/upload-artifact@v4
      with:
        name: node-app-artifact
        path: .

  # 2. TEST
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: node-app-artifact

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install
    - run: npm test

  # 3. DOCKER
  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: 1khushal
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/1khushal/my-node-app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/1khushal/my-node-app:latest

  # 4. SETUP KIND CLUSTER
  setup-cluster:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create KIND cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind

      - name: Export kubeconfig
        run: kind get kubeconfig --name kind > kubeconfig

      - name: Upload kubeconfig artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubeconfig
          path: kubeconfig

  # 5. DEPLOY
  deploy:
    runs-on: ubuntu-latest
    needs: setup-cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create KIND cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind

      - name: Export kubeconfig
        run: kind get kubeconfig --name kind > kubeconfig

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yaml
